# Generated by Django 4.1.7 on 2023-04-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteConsultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('especialidade', models.CharField(choices=[('Alergologia', 'Alergologia'), ('Clínico Geral', 'Clínico Geral'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Ginecologia', 'Ginecologia'), ('Geriatria', 'Geriatria'), ('Mastologia', 'Mastologia'), ('Nefrologia', 'Nefrologia'), ('Neurologia', 'Neurologia'), ('Nutricionista', 'Nutricionista'), ('Nutrologia', 'Nutrologia'), ('Obstetrícia', 'Obstetrícia'), ('Oftalmologia', 'Oftalmologia'), ('Ortopedia', 'Ortopedia'), ('Otorrinolaringologia', 'Otorrinolaringologia'), ('Pediatria', 'Pediatria'), ('Psicologia', 'Psicologia'), ('Psiquiatria', 'Psiquiatria')], max_length=25)),
                ('local', models.CharField(choices=[('Centro Médico do Porto', 'Centro Médico do Porto'), ('Clínica Lisboa', 'Clínica Lisboa'), ('Hospital Vila Nova de Gaia', 'Hospital Vila Nova de Gaia')], max_length=50)),
                ('situacao', models.CharField(choices=[('Solicitada', 'Solicitada'), ('Aprovada', 'Aprovada'), ('Faturada', 'Faturada'), ('Auditada', 'Auditada'), ('Cancelada', 'Cancelada')], default='Solicitada', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('acompanhamento', models.TextField(blank=True)),
            ],
        ),
    ]
